% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Problem 2C},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Problem 2C}
\author{}
\date{\vspace{-2.5em}}

\begin{document}
\maketitle

\section{Setup helper functions}\label{setup-helper-functions}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{source}\NormalTok{(}\StringTok{"utils.R"}\NormalTok{)}
\FunctionTok{library}\NormalTok{(car)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: carData
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(lars)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loaded lars 1.3
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(glmnet)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: Matrix
\end{verbatim}

\begin{verbatim}
## Loaded glmnet 5.0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{load}\NormalTok{(}\StringTok{"../data/tmpData.RData"}\NormalTok{)}
\CommentTok{\# Use analysis\_data[train\_id, ] only. Add focused plots and summaries.}
\NormalTok{train\_df }\OtherTok{\textless{}{-}}\NormalTok{ analysis\_data[train\_id, ]}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lasso\_cv }\OtherTok{\textless{}{-}} \FunctionTok{fit\_cv\_glmnet}\NormalTok{(}
    \AttributeTok{x =}\NormalTok{ x\_train,}
    \AttributeTok{y =}\NormalTok{ y\_train,}
    \AttributeTok{alpha =} \DecValTok{1}\NormalTok{,}
    \AttributeTok{foldid =}\NormalTok{ foldid}
\NormalTok{)}
\FunctionTok{plot}\NormalTok{(lasso\_cv)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{problem2c_files/problem2c_files/figure-latex/lasso-fit-1.pdf}}
Based on the 5-fold cross-validation curve generated for the Lasso
regression model (\(\alpha = 1\)), we observe the relationship between
the tuning parameter \(\lambda\) and the Mean-Squared Error (MSE). The
top axis indicates the number of active (non-zero) predictors retained
in the model at each level of penalization.

\begin{itemize}
\item
  The Cross-Validation Curve: The red dots represent the average CV-MSE
  across the 5 folds for each \(\lambda\) value, with the gray error
  bars denoting one standard error above and below the mean. As
  \(-\log(\lambda)\) increases (moving from left to right, meaning the
  penalty weakens), the MSE initially drops, reaches a minimum, and then
  slightly stabilizes as the model approaches the unpenalized OLS limit.
\item
  Optimal \(\lambda\) (\(\lambda_{\text{min}}\)): The right vertical
  dashed line marks \texttt{lambda.min}, the value that strictly
  minimizes the cross-validation MSE. At this optimal point for
  prediction accuracy (\(-\log(\lambda) \approx 2.4\)), the Lasso
  penalty retains 5 non-zero predictors*.
\item
  Parsimonious \(\lambda\) (\(\lambda_{\text{1se}}\)): The left vertical
  dashed line marks \texttt{lambda.1se}, selected by the
  one-standard-error rule. This value applies a stronger penalty
  (\(-\log(\lambda) \approx 1.67\)) to produce a sparser model. It
  retains only 3 non-zero predictors while keeping the error within one
  standard deviation of the absolute minimum MSE, offering a robust
  trade-off between predictive power and model simplicity.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lasso\_cv}\SpecialCharTok{$}\NormalTok{lambda.min}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.08906571
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lasso\_cv}\SpecialCharTok{$}\NormalTok{lambda}\FloatTok{.1}\NormalTok{se}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.1874748
\end{verbatim}

Lambda = 0: - No regularization - Same result as OLS Lamda.min
\textgreater{} 0 : - Coefficient shrink lightly - All predictors are
kept Lambda large: - Coefficient forced to 0

The exact penalty parameters determined by the cross-validation
procedure are:

lambda.min: 0.0891. This is the penalty value that yields the lowest
training cross-validation MSE (0.5790).

lambda.1se: 0.1875. Following the one-standard-error rule, this is the
largest penalty parameter that keeps the cross-validation error within
one standard deviation of the absolute minimum.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{coef}\NormalTok{(lasso\_cv, }\AttributeTok{s=}\StringTok{"lambda.min"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 9 x 1 sparse Matrix of class "dgCMatrix"
##             lambda.min
## (Intercept) 2.47569468
## lcavol      0.67611312
## lweight     0.12774355
## age         .         
## lbph        0.03085712
## svi         0.20454921
## lcp         .         
## gleason     .         
## pgg45       0.03234366
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{coef}\NormalTok{(lasso\_cv, }\AttributeTok{s=}\StringTok{"lambda.1se"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 9 x 1 sparse Matrix of class "dgCMatrix"
##             lambda.1se
## (Intercept) 2.47569468
## lcavol      0.63661195
## lweight     0.05343261
## age         .         
## lbph        .         
## svi         0.14411468
## lcp         .         
## gleason     .         
## pgg45       .
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{count\_nonzero}\NormalTok{(lasso\_cv, }\AttributeTok{s=}\StringTok{"lambda.min"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 5
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{count\_nonzero}\NormalTok{(lasso\_cv, }\AttributeTok{s=}\StringTok{"lambda.1se"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3
\end{verbatim}

Comparing the active predictors under both tuning rules explicitly
reveals Lasso's capability for exact variable selection:

Under lambda.min: The model retains 5 non-zero predictors (lcavol,
lweight, lbph, svi, and pgg45). The remaining variables (age, lcp, and
gleason) are shrunken completely to zero.

Under lambda.1se: The stronger penalty further simplifies the model by
dropping lbph and pgg45. Only the 3 most statistically robust predictors
are retained as non-zero: lcavol, lweight, svi.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lasso\_cv}\SpecialCharTok{$}\NormalTok{cvm[}
\NormalTok{    lasso\_cv}\SpecialCharTok{$}\NormalTok{lambda}\SpecialCharTok{==}
\NormalTok{    lasso\_cv}\SpecialCharTok{$}\NormalTok{lambda.min}
\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5789934
\end{verbatim}

The value 0.5790 represents the minimum cross-validation Mean-Squared
Error (CV-MSE). It indicates the best predictive accuracy achieved by
the Lasso model during the tuning phase across the 5 shared validation
folds.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lasso\_fit }\OtherTok{\textless{}{-}} \FunctionTok{glmnet}\NormalTok{(}
\NormalTok{    x\_train,}
\NormalTok{    y\_train,}
    \AttributeTok{alpha=}\DecValTok{1}\NormalTok{,}
    \AttributeTok{standardize=}\ConstantTok{FALSE}\NormalTok{,}
      
\NormalTok{)}
\FunctionTok{plot}\NormalTok{(lasso\_fit)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{problem2c_files/problem2c_files/figure-latex/lasso-coef-path-1.pdf}}

\end{document}
